# Couldn't make it work locally, but I'm saving here the attempts I made...
# For trying to run the demo locally, first activate the Windows 8 Administrator account...
net user administrador /active:yes
Add-PSSnapin WDeploySnapin3.0
# Provide the Administrator account credentials when prompted...
$cred = Get-Credential
# Here I get an UnauthorizedAccessException...
New-WDPublishSettings -ComputerName localhost –Credentials $cred -AgentType MSDepSvc -FileName:"C:\Server.publishsettings"
Sync-WDApp "Default Web Site/MyApp" "Default Web Site/MyAppDeployedWithPowerShell" -DestinationPublishSettings "C:\Server.publishsettings"