// <auto-generated />
namespace BlueYonder.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPassportAndAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPassportAndAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201209222102005_AddPassportAndAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
